### ISSUE TITLE
CRITICAL: It is possible to violate a sanity check by calling public  methods.

### ISSUE THREAD

**Issue by I-Hansson** [Simbpa/TDA553-lab1#8]
For example, we can easly change currentSpeed to a value above enginePower.

**Comment by SkepparAbbe** [comment]
How is that possible since incrementspeed can't change currentspeed to above enginepower because of the logic in the method? We don't see any other methods having that power. Anything we're missing?

**Comment by I-Hansson** [comment]
currentSpeed is protected, so we can easily change its values to whatever we want.

**Comment by SkepparAbbe** [comment]
I see, thank you!
